export const COMMAND_NAMES = [
  'doctor',
  'new',
  'variant',
  'ingest',
  'analyze',
  'proxy',
  'beats',
  'validate-edit',
  'preview',
  'approve-edit',
  'grade-stills',
  'approve-color',
  'confirm-rights',
  'grade',
  'render',
  'render-carousel',
  'qc',
  'qc-carousel',
  'photos',
  'approve-photos',
  'status',
] as const;

export type CommandName = (typeof COMMAND_NAMES)[number];
